"""
Core data models for the Agentic File Architect v3.0.

Contains all dataclasses, enums, and type definitions used across
the entire system — file entries, proposed actions, manifests,
cleanup targets, folder context, and usage reports.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path


# ─── Enums ───────────────────────────────────────────────────────


class ActionType(Enum):
    """Type of operation the agent can propose."""
    MOVE = "MOVE"
    DELETE = "DELETE"
    SKIP = "SKIP"
    ARCHIVE = "ARCHIVE"


class FileCategory(Enum):
    """Classification categories for discovered files."""
    CODE_PYTHON = "Code/Python"
    CODE_CPP = "Code/C++"
    CODE_ARDUINO = "Code/Arduino"
    CODE_WEB = "Code/Web"
    CODE_RUST = "Code/Rust"
    CODE_JAVA = "Code/Java"
    CODE_CSHARP = "Code/CSharp"
    CODE_ML = "Code/ML"
    DOCUMENT_PDF = "Document/PDF"
    DOCUMENT_WORD = "Document/Word"
    DOCUMENT_SPREADSHEET = "Document/Spreadsheet"
    MEDIA_IMAGE = "Media/Image"
    MEDIA_VIDEO = "Media/Video"
    MEDIA_AUDIO = "Media/Audio"
    MEDIA_RAW = "Media/RAW"
    ARCHIVE = "Archive"
    DATA_CSV = "Data/CSV"
    DATA_JSON = "Data/JSON"
    DATA_XML = "Data/XML"
    DESIGN_CAD = "Design/CAD"
    DESIGN_3DPRINT = "Design/3DPrint"
    CACHE_COMPILER = "Cache/Compiler"
    CACHE_RUNTIME = "Cache/Runtime"
    CACHE_SYSTEM = "Cache/System"
    INSTALLER = "Installer"
    UNKNOWN = "Unknown"


# ─── File Entry ──────────────────────────────────────────────────


@dataclass
class FileEntry:
    """Represents a discovered file with all extracted metadata.

    Built during Phase 1 (Discovery Scan) by the ScanEngine.
    """
    path: Path
    size_bytes: int
    modified: datetime
    mime_type: str = ""
    content_snippet: str = ""
    filename_tokens: list[str] = field(default_factory=list)
    parent_context: str = ""


# ─── Proposed Action ────────────────────────────────────────────


@dataclass
class ProposedAction:
    """A single proposed file operation in the manifest.

    Generated by the ActionPlanner after classification.
    """
    file: FileEntry
    action: ActionType
    category: str  # String category from classifier (may be FileCategory.value)
    confidence: float
    reasoning: str
    destination: Path | None = None  # None for DELETE/SKIP
    error: str | None = None  # Set if execution fails


# ─── Manifest ───────────────────────────────────────────────────


@dataclass
class Manifest:
    """Complete proposal manifest containing all proposed actions.

    Generated after Phase 2 (Reasoning & Planning) and presented
    to the user at the Approval Gate.
    """
    timestamp: datetime = field(default_factory=datetime.now)
    actions: list[ProposedAction] = field(default_factory=list)
    total_size_freed: int = 0
    scan_directories: list[str] = field(default_factory=list)
    session_id: str = field(default_factory=lambda: uuid.uuid4().hex[:8])
    approval_mode: str | None = None  # Y, N, M, E

    @property
    def moves(self) -> list[ProposedAction]:
        return [a for a in self.actions if a.action == ActionType.MOVE]

    @property
    def deletes(self) -> list[ProposedAction]:
        return [a for a in self.actions if a.action == ActionType.DELETE]

    @property
    def skips(self) -> list[ProposedAction]:
        return [a for a in self.actions if a.action == ActionType.SKIP]

    @property
    def archives(self) -> list[ProposedAction]:
        return [a for a in self.actions if a.action == ActionType.ARCHIVE]


# ─── Cleanup Target ─────────────────────────────────────────────


@dataclass
class CleanupTarget:
    """A file or directory identified for cleanup deletion."""
    path: Path
    category: str
    size: int
    confidence: float
    reasoning: str


# ─── Folder Context (v3.0 FCA) ──────────────────────────────────


@dataclass
class FolderContext:
    """Result of Folder Context Analysis on a directory.

    Describes the detected purpose, category, and recommended
    action for a folder during full-drive scanning.
    """
    path: Path
    category: str
    confidence: float
    reasoning: str
    action: str  # "KEEP_IN_PLACE", "PROPOSE_MOVE", "PROPOSE_CLEANUP", "SKIP"


# ─── Usage Report (v3.0 Smart Usage Brain) ──────────────────────


@dataclass
class UsageReport:
    """Report for a single file's usage/staleness analysis.

    Generated by the UsageBrain when analyzing document usage
    patterns across user directories.
    """
    path: Path
    staleness_score: float
    days_since_access: int
    days_since_modify: int
    size_bytes: int
    has_duplicate: bool
    recommendation: str  # "DELETE", "ARCHIVE", "KEEP"
    reasoning: str
